# .github/workflows/test.yml

name: Run Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"] # Simplified version

    steps:
      # 1. Checks out a copy of your repository's code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Sets up the specified version of Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # 3. Install all dependencies from requirements.txt AND the local package
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install libraries like pandas, pytest, fasthtml, etc.
          pip install -r requirements.txt
          # Install your local employee_events package in editable mode
          pip install -e ./python-package

      # 4. Run the tests using pytest
      - name: Test with pytest
        run: pytest